Repository 777ahesh/Sangeet, pull requests merged in 2022-10, with the labels that each got.

#1 added website logo
  Asset/Sangeet.png
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#10 Started with Home Page
  Asset/Music1.jpg
  Asset/Music2.jpg
  Asset/Music3.jpg
  Asset/song1.png
  index.html
  style.css
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#20 Signup
  Asset/login-background.svg
  index.html
  signup.html
  styles/signup.css
  styles/style.css
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#21 Enhanced home page style, added few songs, social media icons and linked login/signup page.
  Asset/song2.png
  Asset/song3.png
  Asset/song4.png
  Asset/song5.png
  Asset/song6.png
  Asset/song7.png
  Asset/song8.png
  index.html
  signup.html
  styles/signup.css
  styles/style.css
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#30 Made UI responsive
  index.html
  styles/style.css
Labels: enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#32 Made error page
  ERROR_PAGE/index.html
  ERROR_PAGE/style.css
  ERROR_PAGE/styling.js
Labels: enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#35 Modified the color of the website and made some UI changes
  index.html
  styles/login.css
  styles/signup.css
  styles/style.css
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#36 Button Color changed
  styles/style.css
Labels: good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED
